//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int IdNumber { get; set; }
        public int Floor { get; set; }
        public string Type { get; set; }
        public int Size { get; set; }
        public int NumberOfBeds { get; set; }
        public int Price { get; set; }


        public string RoomInformation
        {
            get
            {
                return $"Numer pokoju: { IdNumber }, Piêtro: { Floor }, Typ: { Type }, Metra¿: { Size }, Liczba miejsc: { NumberOfBeds }, Cena: { Price }";
            }
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
